api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

[log.file]
enabled = true
target = true
directory = "."
prefix = "obelisk.log" # File name prefix

[[activity_js]]
name = "activity_js_fetch_get"
location = "${OBELISK_TOML_DIR}/crates/testing/test-programs/js/activity/fetch.js"
ffqn = "testing:js/activity.fetch-get"
params.inline = [{name = "url", type = "string"}]
max_retries = 0
[[activity_js.allowed_host]]
pattern = "http://localhost:5005" # all https is allowed
methods = ["GET"]

[[workflow_js]]
name = "workflow_js_test"
location = "${OBELISK_TOML_DIR}/crates/testing/test-programs/js/workflow/component.js"
ffqn = "testing:js/workflow.fetch-components"
params.inline = []
