# see https://github.com/obeli-sk/components/tree/main/docker/activity-docker
# [activities]
# directories.enabled = true
# [[activity_wasm]]
# name = "activity_docker"
# location = "oci://docker.io/getobelisk/components_docker_activity_docker:2026-02-08@sha256:39607793f16fb9d428bd6dfb91d5d2b310e710fbdf227fb2cf3725b546a64bf2"
# directories  = { enabled = true, process_provider = "native"}

# see https://github.com/obeli-sk/components/tree/main/fly/activity-fly-http
# [[activity_wasm]]
# name = "activity_fly_http"
# location = "oci://docker.io/getobelisk/components_fly_activity_fly_http:2026-02-08@sha256:5daa32a03c563eeaeda48273cc0e12dfec70258bcc435a3fb52b9e12ec169de7"
# exec.lock_expiry.seconds = 15
# env_vars = ["FLY_API_TOKEN"]

# see https://github.com/obeli-sk/components/tree/main/fly/webhook-fly-secrets-updater
# [[webhook_endpoint]]
# name = "webhook_fly_secrets_updater"
# location = "oci://docker.io/getobelisk/components_fly_webhook_fly_secrets_updater:2026-02-08@sha256:e957a9734d13d88861f0abc2a9901367895441c8651bfb6e36e9409dcdd5a06a"
# http_server = "webhook_server"
# routes = [{ methods = ["POST"], route = "/" }]
# env_vars = ["FLY_API_TOKEN"]
#
# [[http_server]]
# name = "webhook_server"
# listening_addr = "0.0.0.0:9090"

# see https://github.com/obeli-sk/components/tree/main/github/activity-github-graphql
# [[activity_wasm]]
# name = "activity_github_graphql"
# location = "oci://docker.io/getobelisk/components_github_activity_github_graphql:2026-02-08@sha256:21f61fa354e05a5df98278c7d7434c87d8eb0838f29814241f9a47a9f079006e"
# exec.lock_expiry.seconds = 5
# env_vars = ["GITHUB_TOKEN"]

# see https://github.com/obeli-sk/components/tree/main/http/activity-http-generic
# [[activity_wasm]]
# name = "activity_http_generic"
# location = "oci://docker.io/getobelisk/components_http_activity_http_generic:2026-02-08@sha256:bfe61f1bbabd67c72086c62446b73b8da330972658dc4282b1e27df23f4624c0"
# exec.lock_expiry.seconds = 5

# see https://github.com/obeli-sk/components/tree/main/obelisk/activity-obelisk-client-http
# [[activity_wasm]]
# name = "activity_obelisk_client_http"
# location = "oci://docker.io/getobelisk/components_obelisk_activity_obelisk_client_http:2026-02-08@sha256:8199bf77e6c0084c843fab116dba929c661b418b231f68e3eb4ddbb342be049c"

# see https://github.com/obeli-sk/components/tree/main/openai/activity-openai-responses
# [[activity_wasm]]
# name = "activity_openai_responses"
# location = "oci://docker.io/getobelisk/components_openai_activity_openai_responses:2026-02-08@sha256:adb87fa3a8f8da5f7d12f203be685aa3ee4ef56a2b2683643da680c543562dea"
# exec.lock_expiry.seconds = 60
# env_vars = ["OPENAI_API_KEY"]

# see https://github.com/obeli-sk/components/tree/main/postmark/activity-postmark-email
# [[activity_wasm]]
# name = "activity_postmark_email"
# location = "oci://docker.io/getobelisk/components_postmark_activity_postmark_email:2026-02-08@sha256:a68b3b22d54fe58f099006801142f32707c2f6abc7f8414ee605986064f7708b"
# exec.lock_expiry.seconds = 30
# env_vars = ["POSTMARK_SERVER_TOKEN"]

# see https://github.com/obeli-sk/components/tree/main/sendgrid/activity-sendgrid-email
# [[activity_wasm]]
# name = "activity_sendgrid_email"
# location = "oci://docker.io/getobelisk/components_sendgrid_activity_sendgrid_email:2026-02-08@sha256:ce3782c627d71be8437ed203959af168969271062559c608f28cc00707e8fd0a"
# exec.lock_expiry.seconds = 30
# env_vars = ["SENDGRID_API_KEY"]
