[toolchain]
channel = "1.93"
targets = [
    "wasm32-unknown-unknown",
    "wasm32-wasip2",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]
components = ["rustfmt", "clippy", "rust-src", "rust-analyzer", "cargo"]
