[package]
name = "test-utils"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
utils.workspace = true

arbitrary.workspace = true
chrono.workspace = true
madsim.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
